Repository f-lab-edu/Prostargram, pull requests merged in 2023-09, with the labels that each got.

#24 Feat/#6 회원가입 및 피드 DTO 작성
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/controller/TestController.java
  src/main/java/flab/project/data/dto/CommentWithUser.java
  src/main/java/flab/project/data/dto/CreateUserAdditionalInfoRequestDto.java
  src/main/java/flab/project/data/dto/CreateUserRequestDto.java
  src/main/java/flab/project/data/dto/PostWithUser.java
  src/main/java/flab/project/data/dto/model/BasePost.java
  src/main/java/flab/project/data/dto/model/BasicPost.java
  src/main/java/flab/project/data/dto/model/BasicUser.java
  src/main/java/flab/project/data/dto/model/Comment.java
  src/main/java/flab/project/data/dto/model/DebatePost.java
  src/main/java/flab/project/data/dto/model/Follows.java
  src/main/java/flab/project/data/dto/model/Option.java
  src/main/java/flab/project/data/dto/model/PollPost.java
  src/main/java/flab/project/data/dto/model/User.java
  src/main/java/flab/project/data/enums/LikeType.java
  src/main/java/flab/project/data/enums/PostType.java
Labels: enhancement

#27 Feat/#26 관심사 추가/삭제 기능 구현
  build.gradle
  src/main/java/flab/project/ApiControllerAdvice.java
  src/main/java/flab/project/common/BadWordChecker.java
  src/main/java/flab/project/config/Constraint.java
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/config/exception/NumberLimitOfInterestExceededException.java
  src/main/java/flab/project/controller/InterestController.java
  src/main/java/flab/project/data/dto/AddInterest.java
  src/main/java/flab/project/data/dto/model/HashTag.java
  src/main/java/flab/project/facade/InterestFacade.java
  src/main/java/flab/project/mapper/BadWordMapper.java
  src/main/java/flab/project/mapper/HashTagMapper.java
  src/main/java/flab/project/mapper/InterestMapper.java
  src/main/java/flab/project/service/HashTagService.java
  src/main/java/flab/project/service/InterestService.java
  src/main/resources/mapper/flab/project/mapper/badword-mapper.xml
  src/main/resources/mapper/flab/project/mapper/hashtag-mapper.xml
  src/main/resources/mapper/flab/project/mapper/interest-mapper.xml
  src/test/java/flab/project/controller/InterestControllerTest.java
  src/test/java/flab/project/data/dto/AddInterestTest.java
  src/test/java/flab/project/facade/InterestFacadeTest.java
  src/test/java/flab/project/service/HashTagServiceTest.java
  src/test/java/flab/project/service/InterestServiceTest.java
Labels: enhancement

#42 feat/#41 유저 계정 공개범위 수정 기능 구현
  src/main/java/flab/project/ApiControllerAdvice.java
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/controller/SettingController.java
  src/main/java/flab/project/mapper/SettingMapper.java
  src/main/java/flab/project/service/SettingService.java
  src/main/resources/mapper/flab/project/mapper/setting-mapper.xml
  src/test/java/flab/project/controller/SettingControllerTest.java
  src/test/java/flab/project/service/SettingServiceTest.java
Labels: enhancement

#37 Feat/#32 프로필 정보 수정 기능 구현
  src/main/java/flab/project/ApiControllerAdvice.java
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/controller/UserController.java
  src/main/java/flab/project/data/dto/UpdateProfileRequestDto.java
  src/main/java/flab/project/mapper/UserMapper.java
  src/main/java/flab/project/service/UserService.java
  src/main/resources/mapper/flab/project/mapper/follow-mapper.xml
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
  src/test/java/flab/project/controller/UserControllerTest.java
  src/test/java/flab/project/service/UserServiceTest.java
Labels: enhancement

#39 feat/#38 프로필 정보 가져오기 기능 구현
  src/main/java/flab/project/ApiControllerAdvice.java
  src/main/java/flab/project/config/baseresponse/SuccessResponse.java
  src/main/java/flab/project/config/exception/InvalidUserInputException.java
  src/main/java/flab/project/config/exception/NotExistUserException.java
  src/main/java/flab/project/controller/UserController.java
  src/main/java/flab/project/data/dto/GetProfilePageResponseDto.java
  src/main/java/flab/project/data/dto/model/Profile.java
  src/main/java/flab/project/data/dto/model/SocialAccountResponse.java
  src/main/java/flab/project/data/enums/requestparam/GetProfileRequestType.java
  src/main/java/flab/project/mapper/UserMapper.java
  src/main/java/flab/project/service/UserService.java
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
  src/test/java/flab/project/controller/UserControllerTest.java
  src/test/java/flab/project/service/UserServiceTest.java
Labels: enhancement

#44 Feat/#43 개인 설정 상태 정보 확인하는 기능 구현
  src/main/java/flab/project/ApiControllerAdvice.java
  src/main/java/flab/project/config/exception/NotExistUserException.java
  src/main/java/flab/project/controller/SettingController.java
  src/main/java/flab/project/mapper/SettingMapper.java
  src/main/java/flab/project/service/SettingService.java
  src/main/resources/mapper/flab/project/mapper/setting-mapper.xml
  src/test/java/flab/project/controller/SettingControllerTest.java
  src/test/java/flab/project/service/SettingServiceTest.java
Labels: enhancement

#46 Feat/#45 라이트/다크 모드 기능 구현
  build.gradle
  src/main/java/flab/project/controller/SettingController.java
  src/main/java/flab/project/data/enums/ScreenMode.java
  src/main/java/flab/project/service/SettingService.java
  src/test/java/flab/project/controller/SettingControllerTest.java
  src/test/java/flab/project/controller/SettingIntegrationTest.java
Labels: enhancement

#25 Feat/#18 게시물 좋아요 기능 구현
  src/main/java/flab/project/ApiControllerAdvice.java
  src/main/java/flab/project/ProjectApplication.java
  src/main/java/flab/project/config/exception/InvalidUserInputException.java
  src/main/java/flab/project/controller/LikeController.java
  src/main/java/flab/project/data/dto/CreateUserAdditionalInfoRequestDto.java
  src/main/java/flab/project/data/dto/CreateUserRequestDto.java
  src/main/java/flab/project/mapper/LikeMapper.java
  src/main/java/flab/project/service/LikeService.java
  src/main/resources/mapper/flab/project/mapper/like-mapper.xml
  src/test/java/flab/project/controller/LikeControllerTest.java
  src/test/java/flab/project/service/FollowServiceUnitTest.java
  src/test/java/flab/project/service/LikeServiceTest.java
Labels: enhancement

#34 Feat/#33 프로필 이미지 수정 기능 구현
  build.gradle
  src/main/java/flab/project/ApiControllerAdvice.java
  src/main/java/flab/project/common/FileStorage/FileExtensionExtractor.java
  src/main/java/flab/project/common/FileStorage/FileExtensionFilter.java
  src/main/java/flab/project/common/FileStorage/FileFactory.java
  src/main/java/flab/project/common/FileStorage/FileStorage.java
  src/main/java/flab/project/config/FileStorageConfig.java
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/config/exception/FailedToUpdateProfileImageToDatabaseException.java
  src/main/java/flab/project/config/exception/NotImageExtensionOrNotSupportedExtensionException.java
  src/main/java/flab/project/controller/UserController.java
  src/main/java/flab/project/data/dto/file/ProfileImage.java
  src/main/java/flab/project/data/dto/file/Uploadable.java
  src/main/java/flab/project/data/enums/ExtensionType.java
  src/main/java/flab/project/data/enums/FileType.java
  src/main/java/flab/project/facade/UserFacade.java
  src/main/java/flab/project/mapper/FileExtensionMapper.java
  src/main/java/flab/project/mapper/UserMapper.java
  src/main/java/flab/project/service/UserService.java
  src/main/resources/mapper/flab/project/mapper/file-extension-mapper.xml
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
  src/test/java/flab/project/common/FileStorage/FileExtensionExtractorTest.java
  src/test/java/flab/project/common/FileStorage/FileExtensionFilterTest.java
  src/test/java/flab/project/common/FileStorage/FileFactoryTest.java
  src/test/java/flab/project/controller/UserControllerTest.java
  src/test/java/flab/project/data/dto/file/ProfileImageTest.java
  src/test/java/flab/project/facade/UserFacadeTest.java
  src/test/java/flab/project/service/UserServiceTest.java
Labels: enhancement

#35 ISSUE Template 변경
  .github/ISSUE_TEMPLATE/custom.md
Labels: documentation

#54 [feat] 게시물 상세보기 기능 구현
  build.gradle
  src/main/java/flab/project/ApiControllerAdvice.java
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/controller/PostController.java
  src/main/java/flab/project/data/dto/PostWithUser.java
  src/main/java/flab/project/data/dto/model/BasePost.java
  src/main/java/flab/project/data/dto/model/BasicPost.java
  src/main/java/flab/project/data/dto/model/DebatePost.java
  src/main/java/flab/project/data/dto/model/Option.java
  src/main/java/flab/project/data/dto/model/PollPost.java
  src/main/java/flab/project/mapper/PostMapper.java
  src/main/java/flab/project/mapper/UserMapper.java
  src/main/java/flab/project/service/PostService.java
  src/main/resources/mapper/flab/project/mapper/post-mapper.xml
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
  src/test/java/flab/project/controller/PostControllerTest.java
  src/test/java/flab/project/service/PostServiceTest.java
Labels: enhancement

#50 [refactor] 팔로우 Service 로직 수정
  src/main/java/flab/project/service/FollowService.java
  src/test/java/flab/project/service/FollowServiceUnitTest.java
Labels: refactoring

#52 [refactor] refactor interestFacade logic
  src/main/java/flab/project/facade/InterestFacade.java
Labels: refactoring
