Repository f-lab-edu/Prostargram, pull requests merged in 2024-09, with the labels that each got.

#139 [#138]
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/domain/user/controller/FollowController.java
Labels: documentation

#141 [#140] 팔로워/팔로잉 추가 및 삭제 Swagger 작성
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/domain/user/controller/FollowController.java
Labels: documentation

#146 Prometheus, Grafana 세팅
  build.gradle
  src/main/java/flab/project/config/SecurityConfig.java
Labels: enhancement

#144 [#143] 팔로워/팔로잉 관련 Swagger 수정
  src/main/java/flab/project/domain/user/controller/FollowController.java
Labels: documentation, refactoring

#148 [#147] 중복된 PostLikeMapperTest 삭제
  src/test/java/flab/project/mapper/PostLikeMapperTest.java
Labels: chore

#154 [refactor] 서브 모듈 관련 내용 추가
  build.gradle
Labels: enhancement

#150 [#149] 댓글 좋아요 추가 및 삭제 API 구현
  src/main/java/flab/project/config/SecurityConfig.java
  src/main/java/flab/project/config/SwaggerConfig.java
  src/main/java/flab/project/domain/like/controller/CommentLikeController.java
  src/main/java/flab/project/domain/like/mapper/CommentLikeMapper.java
  src/main/java/flab/project/domain/like/service/CommentLikeService.java
  src/main/java/flab/project/domain/post/controller/BasicPostController.java
  src/main/java/flab/project/domain/post/model/AddBasicPostRequest.java
  src/main/java/flab/project/domain/user/service/CustomUserDetailsService.java
  src/main/resources/mapper/flab/project/mapper/comment-like-mapper.xml
  src/main/resources/mapper/flab/project/mapper/post-like-mapper.xml
Labels: enhancement

#156 [#155] 댓글 가져오기 API에서 사용하는 userId를 jwt의 userId로 수정.
  .dockerignore
  .gitignore
  src/main/java/flab/project/domain/comment/controller/CommentController.java
  src/main/java/flab/project/domain/post/model/AddPostRequest.java
  src/test/java/flab/project/controller/SocialAccountsControllerTest.java
  src/test/java/flab/project/controller/UserControllerTest.java
  src/test/java/flab/project/utils/PostRedisUtilTest.java
Labels: chore

#160 [refactor] FanOut Server를 위한 코드 제거
  src/main/java/flab/project/domain/feed/controller/RabbitMQConsumer.java
  src/main/java/flab/project/domain/feed/service/NewsFeedFanOutService.java
  src/main/java/flab/project/domain/user/mapper/FollowMapper.java
  src/main/java/flab/project/domain/user/service/FollowService.java
  src/main/java/flab/project/utils/FollowerRedisUtil.java
  src/main/java/flab/project/utils/NewsFeedRedisUtil.java
  src/test/java/flab/project/domain/user/mapper/FollowMapperTest.java
Labels: enhancement

#162 [#149] 댓글 좋아요 추가 및 취소 Swagger 작성
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/domain/like/controller/CommentLikeController.java
Labels: documentation, enhancement

#165 [#161] 게시물 생성 시 image file이 아닌 upload할 파일 개수만 전달받고 preSignedUrl을 반환하는 방식으로 수정
  src/main/java/flab/project/common/FileStorage/FileStorage.java
  src/main/java/flab/project/common/FileStorage/UploadedFileUrl.java
  src/main/java/flab/project/common/FileStorage/UploadedFileUrls.java
  src/main/java/flab/project/domain/file/enums/FileType.java
  src/main/java/flab/project/domain/post/controller/BasicPostController.java
  src/main/java/flab/project/domain/post/facade/BasicPostFacade.java
  src/main/java/flab/project/domain/post/model/AddBasicPostRequest.java
  src/main/java/flab/project/domain/post/model/BasicPost.java
  src/main/resources/mapper/flab/project/mapper/post-mapper.xml
  src/test/java/flab/project/controller/BasicPostControllerTest.java
  src/test/java/flab/project/facade/BasicPostFacadeTest.java
  src/test/java/flab/project/facade/DebatePostFacadeTest.java
  src/test/java/flab/project/facade/PollPostFacadeTest.java
  src/test/java/flab/project/mapper/PostMapperTest.java
Labels: refactoring

#167 [#166] 프로필 이미지 수정 시 image file이 아닌 preSignedUrl을 반환하는 방식으로 수정
  src/main/java/flab/project/common/FileStorage/BucketUtils.java
  src/main/java/flab/project/common/FileStorage/FileExtensionExtractor.java
  src/main/java/flab/project/common/FileStorage/FileExtensionFilter.java
  src/main/java/flab/project/common/fileStorage/FileStorage.java
  src/main/java/flab/project/common/fileStorage/UploadedFileUrl.java
  src/main/java/flab/project/common/fileStorage/UploadedFileUrls.java
  src/main/java/flab/project/domain/file/model/File.java
  src/main/java/flab/project/domain/file/model/Uploadable.java
  src/main/java/flab/project/domain/post/facade/BasicPostFacade.java
  src/main/java/flab/project/domain/post/model/BasicPost.java
  src/main/java/flab/project/domain/user/controller/UserController.java
  src/main/java/flab/project/domain/user/facade/UserFacade.java
  src/test/java/flab/project/common/FileStorage/BucketUtilsTest.java
  src/test/java/flab/project/common/FileStorage/FileExtensionExtractorTest.java
  src/test/java/flab/project/common/FileStorage/FileExtensionFilterTest.java
  src/test/java/flab/project/controller/UserControllerTest.java
  src/test/java/flab/project/data/dto/file/FileTest.java
  src/test/java/flab/project/facade/BasicPostFacadeTest.java
  src/test/java/flab/project/facade/UserFacadeTest.java
  src/test/java/flab/project/service/NewsFeedServiceTest.java
  src/test/java/flab/project/service/PostServiceTest.java
Labels: refactoring

#164 [#163] 댓글 작성 및 조회 API Swagger 작성
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/domain/comment/controller/CommentController.java
  src/main/java/flab/project/domain/like/controller/CommentLikeController.java
  src/main/java/flab/project/domain/user/controller/FollowController.java
Labels: documentation

#169 [#168] FollowController userId 검증 로직 추가 및 로직 수정
  src/main/java/flab/project/domain/user/controller/FollowController.java
  src/main/java/flab/project/domain/user/model/User.java
  src/main/java/flab/project/domain/user/service/FollowService.java
  src/test/java/flab/project/controller/FollowControllerUnitTest.java
Labels: refactoring

#171 [#170] 일반 게시물 작성 API Swagger
  src/main/java/flab/project/config/baseresponse/ResponseEnum.java
  src/main/java/flab/project/domain/post/controller/BasicPostController.java
Labels: documentation
