Repository f-lab-edu/Prostargram, pull requests merged in 2024-11, with the labels that each got.

#214 [#212] SwaggerConfig 수정
  src/main/java/flab/project/config/SwaggerConfig.java
Labels: documentation

#216 [#215] POST Http status code 201 수정
  src/main/java/flab/project/domain/comment/controller/CommentController.java
  src/main/java/flab/project/domain/like/controller/CommentLikeController.java
  src/main/java/flab/project/domain/like/controller/PostLikeController.java
  src/main/java/flab/project/domain/post/controller/BasicPostController.java
  src/main/java/flab/project/domain/post/controller/DebatePostController.java
  src/main/java/flab/project/domain/post/controller/PollPostController.java
  src/main/java/flab/project/domain/post/controller/VoteController.java
  src/main/java/flab/project/domain/user/controller/FollowController.java
  src/main/java/flab/project/domain/user/controller/InterestController.java
  src/main/java/flab/project/domain/user/controller/SocialAccountController.java
Labels: documentation

#218 [#217] FollowController 리팩토링
  src/main/java/flab/project/domain/user/controller/FollowController.java
  src/main/resources/mapper/flab/project/mapper/follow-mapper.xml
Labels: documentation

#220 [#219] CommentController 리팩토링
  src/main/java/flab/project/domain/comment/controller/CommentController.java
Labels: documentation

#222 [Refactor] 피드 읽기 버그 수정
  src/main/java/flab/project/common/model/PaginationModel.java
  src/main/java/flab/project/config/SwaggerConfig.java
  src/main/java/flab/project/domain/feed/controller/NewsFeedController.java
  src/main/java/flab/project/domain/feed/model/PostIdsAndHasNext.java
  src/main/java/flab/project/domain/feed/service/NewsFeedService.java
  src/main/java/flab/project/domain/like/mapper/PostLikeMapper.java
  src/main/java/flab/project/domain/like/model/PostLike.java
  src/main/java/flab/project/domain/like/service/PostLikeService.java
  src/main/java/flab/project/domain/post/mapper/PostMapper.java
  src/main/java/flab/project/domain/post/model/BasePost.java
  src/main/java/flab/project/domain/post/service/PostService.java
  src/main/java/flab/project/domain/user/mapper/FollowMapper.java
  src/main/java/flab/project/domain/user/service/FollowService.java
  src/main/java/flab/project/domain/user/service/UserService.java
  src/main/java/flab/project/utils/NewsFeedRedisUtil.java
  src/main/resources/mapper/flab/project/mapper/follow-mapper.xml
  src/main/resources/mapper/flab/project/mapper/post-like-mapper.xml
  src/main/resources/mapper/flab/project/mapper/post-mapper.xml
  src/test/java/flab/project/controller/SettingControllerTest.java
  src/test/java/flab/project/domain/like/mapper/PostLikeMapperTest.java
  src/test/java/flab/project/domain/user/mapper/FollowMapperTest.java
  src/test/java/flab/project/service/NewsFeedServiceTest.java
  src/test/java/flab/project/service/SettingServiceTest.java
Labels: refactoring

#226 [Feat] 게시물 삭제 기능 구현
  src/main/java/flab/project/domain/post/controller/PostController.java
  src/main/java/flab/project/domain/post/mapper/PostMapper.java
  src/main/java/flab/project/domain/post/service/PostService.java
  src/main/java/flab/project/utils/PostRedisUtil.java
  src/main/resources/mapper/flab/project/mapper/post-mapper.xml
Labels: enhancement

#228 [Refactor] TokenDto에 userId 추가
  src/main/java/flab/project/domain/user/model/TokenDto.java
  src/main/java/flab/project/domain/user/service/AuthService.java
Labels: refactoring
