Repository f-lab-edu/Prostargram, pull requests merged in 2024-08, with the labels that each got.

#101 [#97] UserMapper 테스트 작성
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
  src/main/resources/tableInit.sql
  src/test/java/flab/project/mapper/UserMapperTest.java
Labels: enhancement, test

#102 [#98] PostMapper 테스트 작성
  src/main/resources/mapper/flab/project/mapper/poll-metadata-mapper.xml
  src/test/java/flab/project/mapper/PostMapperTest.java
Labels: enhancement, test

#95 [#94] FollowMapper 테스트 작성
  src/main/java/flab/project/domain/user/model/Follows.java
  src/main/resources/mapper/flab/project/mapper/follow-mapper.xml
  src/main/resources/tableInit.sql
  src/test/java/flab/project/controller/FollowControllerUnitTest.java
  src/test/java/flab/project/domain/user/mapper/FollowMapperTest.java
  src/test/java/flab/project/service/FollowServiceUnitTest.java
Labels: enhancement

#107 [#99] 좋아요/좋아요 취소 기능 구현
  src/main/java/flab/project/ApiControllerAdvice.java
  src/main/java/flab/project/config/baseresponse/BaseResponse.java
  src/main/java/flab/project/config/baseresponse/FailResponse.java
  src/main/java/flab/project/domain/like/controller/LikeController.java
  src/main/java/flab/project/domain/like/controller/PostLikeController.java
  src/main/java/flab/project/domain/like/mapper/PostLikeMapper.java
  src/main/java/flab/project/domain/like/service/LikeService.java
  src/main/java/flab/project/domain/like/service/PostLikeService.java
  src/main/java/flab/project/domain/post/mapper/PostMapper.java
  src/main/resources/mapper/flab/project/mapper/like-mapper.xml
  src/test/java/flab/project/TestConstant.java
  src/test/java/flab/project/controller/PostLikeControllerTest.java
  src/test/java/flab/project/domain/like/mapper/PostLikeMapperTest.java
  src/test/java/flab/project/service/PostLikeServiceTest.java
Labels: enhancement

#67 [#65] 댓글 조회 기능 구현
  src/main/java/flab/project/domain/comment/controller/CommentController.java
  src/main/java/flab/project/domain/comment/mapper/CommentMapper.java
  src/main/java/flab/project/domain/comment/model/Comment.java
  src/main/java/flab/project/domain/comment/model/CommentWithUser.java
  src/main/java/flab/project/domain/comment/service/CommentService.java
  src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
  src/test/java/flab/project/controller/CommentControllerTest.java
  src/test/java/flab/project/service/CommentServiceTest.java
Labels: enhancement

#108 [#104] SocialAccountMapper, IconMapper 테스트 작성
  src/main/java/flab/project/domain/user/mapper/IconMapper.java
  src/main/java/flab/project/domain/user/model/Icon.java
  src/main/java/flab/project/domain/user/service/IconService.java
  src/main/resources/mapper/flab/project/mapper/icon-mapper.xml
  src/main/resources/mapper/flab/project/mapper/socialaccount-mapper.xml
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
  src/main/resources/tableInit.sql
  src/test/java/flab/project/controller/VoteControllerTest.java
  src/test/java/flab/project/domain/user/mapper/IconMapperTest.java
  src/test/java/flab/project/domain/user/mapper/SocialAccountMapperTest.java
  src/test/java/flab/project/service/IconServiceTest.java
Labels: enhancement

#109 [#105] InterestMapeer 테스트 작성
  src/main/java/flab/project/domain/user/controller/InterestController.java
  src/main/java/flab/project/domain/user/facade/InterestFacade.java
  src/main/java/flab/project/domain/user/mapper/InterestMapper.java
  src/main/java/flab/project/domain/user/service/InterestService.java
  src/main/resources/mapper/flab/project/mapper/interest-mapper.xml
  src/test/java/flab/project/controller/InterestControllerTest.java
  src/test/java/flab/project/mapper/InterestMapperTest.java
  src/test/java/flab/project/service/InterestServiceTest.java
Labels: enhancement, test

#111 [#110] PostLikeMapper 테스트 작성
  src/test/java/flab/project/mapper/PostLikeMapperTest.java
Labels: enhancement, test

#113 [#112] CommentMapper 테스트 작성
  src/test/java/flab/project/mapper/CommentMapperTest.java
Labels: enhancement, test

#120 [#119] 이메일 인증 코드 전송 API Swagger 작성
  src/main/java/flab/project/config/SwaggerConfig.java
  src/main/java/flab/project/config/baseresponse/BaseResponse.java
  src/main/java/flab/project/domain/user/controller/VerificationController.java
Labels: documentation

#124 [refactor] 이메일 인증 코드 요청 API 수정
  src/main/java/flab/project/domain/user/controller/VerificationController.java
  src/main/java/flab/project/domain/user/exception/ExistedAccountException.java
  src/main/java/flab/project/domain/user/mapper/UserMapper.java
  src/main/java/flab/project/domain/user/service/VerificationService.java
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
  src/test/java/flab/project/mapper/UserMapperTest.java
Labels: refactoring

#127 [#126] 닉네임 중복 확인 API Swagger 작성
  src/main/java/flab/project/domain/user/controller/DuplicationController.java
  src/main/java/flab/project/domain/user/controller/UsernameDuplicationController.java
  src/main/java/flab/project/domain/user/exception/ExistedUsernameException.java
  src/main/java/flab/project/domain/user/mapper/DuplicationMapper.java
  src/main/java/flab/project/domain/user/mapper/UserMapper.java
  src/main/java/flab/project/domain/user/service/DuplicationService.java
  src/main/java/flab/project/domain/user/service/UsernameDuplicationService.java
  src/main/resources/mapper/flab/project/mapper/duplication-mapper.xml
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
Labels: documentation, refactoring

#128 [#114] 회원가입 Swagger 작성
  src/main/java/flab/project/domain/user/controller/SignUpController.java
  src/main/java/flab/project/domain/user/exception/InvalidEmailTokenException.java
  src/main/java/flab/project/domain/user/exception/InvalidUsernameTokenException.java
  src/main/java/flab/project/domain/user/model/SignUp.java
  src/main/java/flab/project/domain/user/service/SignUpService.java
Labels: documentation, refactoring

#130 [#129] 회원가입 관련 API Swagger 마무리
  src/main/java/flab/project/config/SecurityConfig.java
  src/main/java/flab/project/domain/user/controller/SignUpController.java
  src/main/java/flab/project/domain/user/controller/UsernameDuplicationController.java
  src/main/java/flab/project/domain/user/controller/VerificationController.java
  src/main/java/flab/project/domain/user/model/EmailTokenReturnDto.java
  src/main/java/flab/project/domain/user/model/UsernameTokenReturnDto.java
  src/main/java/flab/project/domain/user/service/UsernameDuplicationService.java
  src/main/java/flab/project/domain/user/service/VerificationService.java
Labels: documentation

#132 [docs] Swagger 작성
  src/main/java/flab/project/common/annotation/LoggedInUserId.java
  src/main/java/flab/project/domain/user/controller/AuthController.java
  src/main/java/flab/project/domain/user/model/FormLoginRequest.java
  src/main/java/flab/project/domain/user/model/TokenDto.java
  src/main/java/flab/project/domain/user/service/AuthService.java
Labels: documentation
