Repository f-lab-edu/Prostargram, pull requests merged in 2024-10, with the labels that each got.

#187 [feat] 토론 게시물 작성 API Swagger 작성
  src/main/java/flab/project/domain/post/controller/DebatePostController.java
Labels: documentation

#190 [feat] 통계 게시물 작성 API Swagger 작성
  src/main/java/flab/project/domain/post/controller/PollPostController.java
Labels: documentation

#192 [#191] 피드 조회 API 버그 수정
  src/main/java/flab/project/common/file_storage/FileUploader.java
  src/main/java/flab/project/common/file_storage/UploadedFileUrl.java
  src/main/java/flab/project/common/file_storage/UploadedFileUrls.java
  src/main/java/flab/project/domain/feed/service/NewsFeedService.java
  src/main/java/flab/project/domain/post/facade/BasicPostFacade.java
  src/main/java/flab/project/domain/post/model/BasicPost.java
  src/main/java/flab/project/domain/user/controller/UserController.java
  src/main/java/flab/project/domain/user/facade/UserFacade.java
  src/main/java/flab/project/domain/user/service/UserService.java
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
  src/test/java/flab/project/controller/UserControllerTest.java
  src/test/java/flab/project/facade/BasicPostFacadeTest.java
  src/test/java/flab/project/facade/UserFacadeTest.java
Labels: bug

#194 [#189] 게시물 상세 보기 API Swagger 작성 및 로직 수정
  src/main/java/flab/project/config/exception/NotFoundException.java
  src/main/java/flab/project/domain/post/controller/PostController.java
  src/main/java/flab/project/domain/post/service/PostService.java
  src/main/java/flab/project/domain/post/service/VoteService.java
Labels: documentation, refactoring

#195 [#193] 깨진 Test 수정
  src/main/resources/mapper/flab/project/mapper/socialaccount-mapper.xml
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
  src/main/resources/tableInit.sql
  src/test/java/flab/project/controller/CommentControllerTest.java
  src/test/java/flab/project/service/NewsFeedServiceTest.java
Labels: bug

#198 [#193] 깨진 테스트 해결
  src/main/resources/mapper/flab/project/mapper/user-mapper.xml
  src/main/resources/tableInit.sql
Labels: bug

#202 [fix] processResource가 copyPrivate 이후에 실행되도록 설정
  build.gradle
Labels: bug

#205 [#204] existsById 구현
  src/main/resources/mapper/flab/project/mapper/post-mapper.xml
Labels: enhancement

#208 [fix] swagger Authorization button 추가
  src/main/java/flab/project/config/SwaggerConfig.java
Labels: bug
